Add aiff support
y-brehm/waveAlign pull request #1
Opened 2023-03-13 11:19 UTC by SimonZimmer

Adds `aiff` support and album-art retention.
Additionally:
* Consolidate read and write to `soundfile` library and remove `librosa`
* Remove unused field from `AudioFileSpecSet`

2023-03-13 18:23 UTC, y-brehm requested changes
Only a missing user notification in case of a non-supported file format, and one further separation of responsibilities.

2023-03-13 18:23 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
This should notify the user in case the file extension is not supported.

2023-03-13 18:23 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_handler.py
> +    metadata.save()
I know we are still under 50 lines in this file, but IMO we could already further separate into `generate_audio_spec_set.py` and an `write_audio_file.py`.

I don't really see why you deleted the generate_audio_spec_set.py file in the first place. This file now has two responsibilities: Reading files and writing files.

2023-03-13 18:23 UTC, y-brehm commented on src/wavealign/data_collection/generate_audio_spec_set.py
> -
As mentioned above I don't understand why you deleted this. IMO reading and writing audio files should happen in separate files.

2023-03-13 20:19 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
Well, then the question is which would be files that the user potentially will assume are supported.
.ogg ? .flac?
I think it is better to just have a defined list of supported codecs and then only include them in the scanning process, ignoring the rest since this is at least clearly defined.

2023-03-13 20:23 UTC, SimonZimmer commented on src/wavealign/data_collection/generate_audio_spec_set.py
> -
To me, a reader and writer are one operation and the same operation inverted.
If it can be expressed with little complexity as is the case here, I don't see a reason to split

2023-03-14 07:50 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
Hmm, from a user perspective, I would be quite annoyed if some of my files are not processed because they have the wrong format. I might actually not even know that I have those files in my library. During a gig, this could be lethal, if I assume that my whole library was processed. 
What about adding all ignored files to a list and printing this at the end of the processing, or saving them in a log file? We could scan for all regular audio formats and ignore the rest. 
I completely get your point, but I think in the long term we have to build in some usability features like this. Not all people that we target with this are developers.
If you think this should not belong to the scope of this PR, then maybe let's create another issue.

2023-03-14 08:02 UTC, y-brehm approved these changes
As mentioned: I disagree but approve. 😄

2023-03-14 08:04 UTC, maosi100 commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
I agree with @y-brehm that some kind of user notification would certainly make sense as a quality of life feature. However printing all unprocessed files would potentially open the gates to some documentational clutter.

So what about notifying the user during processing start which file formats are supported and after processing just printing a tally of processed files / all files in specified filepath?

2023-03-14 10:33 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
Hmm yeah, printing all unprocessed files doesn't make sense IMO since there could be basically anything non-audio related in the input folder, so I think this ultimately comes down to defining two lists:
A) "regular" audio formats that could potentially be used
B) audio formats that we support
If there is any file that is included in A) but not in B), we can let the user know that this is happening.

But here is the thing:
Shouldn't A) and B) be the same because we want to support all regular audio files?

Here are the files officially supported by rekordbox:
FLAC, ALAC, WAV, AIFF, MP3, and AAC (https://support.pioneerdj.com/hc/en-us/articles/4409711023897-What-file-formats-are-supported-rekordbox-)

IMO, we should aim to support all of these with this tool, state that in the docs and ignore everything else. If the user has files in his music collection that can't be used with rekordbox, what would be the point in flagging that?

2023-03-14 10:48 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
@SimonZimmer 
I agree: We should fully support all files that rekordbox supports. But if we don't do that until release 1.0, we have to add some kind of mechanism to tell the user that some of his files were not processed (if so).
So I guess we should create issues to support all the formats you just mentioned to resolve this.

2023-03-14 11:44 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_file_finder.py
> +                    wav_files.append(os.path.join(root, file_name))
Yes, that's true.
According to soundfile's documentation, All of the rekordbox formats are also supported by the library, so it shouldn't be an issue to aim for that with 1.0
I created an issue for supporting all of them: https://github.com/y-brehm/waveAlign/issues/7
If you guys agree that this should be a included in 1.0 I think we can conclude

2023-03-14 14:02 UTC, merged