Issue/#2/add unit tests main functions
y-brehm/waveAlign pull request #11
Opened 2023-03-22 19:12 UTC by maosi100

- first draft of wave_align() tests, happy to adjust according to your feedback
- if the functions within batch_process_files.py need to be tested let me know
- there's also changes in align_waveform_to_target.py because I failed to rebase properly (will now just use merge instead of rebase as it worked fine in the past)

2023-03-23 16:50 UTC, SimonZimmer requested changes
Great job in isolating each of the logic branches into their own test case 🏅 
Some notes for test accuracy and readability

2023-03-23 16:50 UTC, SimonZimmer commented on tests/unit/wavealign/test_wave_alignment.py
> +        mock_find.assert_called_once_with(self.fake_input_path)
This works for us mac users, because `os.path.normpath` will transform `/my/dir` into `/my/dir` aka not modify it at all. However, if you execute this on Windows, os.normpath might transform this to `\\my\\dir` because it wants to ensure interoperability of paths between operating systems and windows uses a different syntax.
As a result the test will succeed on Mac but fail on Windows.
Once we build this application for windows which we likely will at some point, we need to also run tests on windows.

So it would be safer to mock os.path.normpath as well and let it return a fake path which you can then use to set expectations on

2023-03-23 16:50 UTC, SimonZimmer commented on tests/unit/wavealign/test_wave_alignment.py
> +        mock_read.assert_called_once_with(*mock_find.return_value)
If I remove the line `if read_only is False:` from `wave_alignment.py`, this test would actually still pass, because `find` and `read` would still both be called.
That means, the test is not precise enough.

At a minimum, we should mock `write` as well and then add this expectation:
```python
mock_write.assert_not_called()
```
If we want to be really precise we would also test that `align_waveform_to_target` and `detect_peak` are also not called here.

2023-03-23 16:50 UTC, SimonZimmer commented on tests/unit/wavealign/test_wave_alignment.py
> +        mock_read.return_value = self.fake_audio_file_spec_set
Since you are specifying these two return values in every test, you can make it more readable by patching the `find` and `read` mocks in the `setUp` method and defining the return values in there.
Then, you can just pass `mock_find` and `mock_read` in every test method without defining return values each time.

2023-03-23 16:50 UTC, SimonZimmer commented on tests/unit/wavealign/test_wave_alignment.py
> +        wave_alignment(
In the event that something goes wrong in the implementation and the assertion is wrongly raised for this case, the test would crash, outputting the assertion.
A more accurate behaviour in this situation would be for the test to fail indicating that the assertion was raised where it shouldn't have been.
This could be encoded into something like:
```python
    try:
        wave_alignment(
        ...
        )
    except Exception:
        self.fail("wav_alignment() raised Exception unexpectedly")
```

2023-03-23 19:54 UTC, maosi100 commented
Thanks @SimonZimmer for this comprehensive feedback, very helpful! 💘

I've added everything you've requested in the newest commit.

2023-03-24 11:30 UTC, SimonZimmer approved these changes

2023-03-24 11:31 UTC, SimonZimmer commented
@maosi100 
Awesome, thanks!
This looks very secure to me now ❤️

2023-03-24 12:51 UTC, merged

2023-03-24 12:53 UTC, y-brehm reviewed
Nice!