test for align_waveform_to_target.py
y-brehm/waveAlign pull request #12
Opened 2023-04-02 12:12 UTC by maosi100

2023-04-16 13:51 UTC, y-brehm requested changes
YAGNI!!!! You basically did way too much. I would simplify this test a lot!

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +
additional new line

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +            file_path='/my/dir/fake_file_1.wav',
not super necessary, but I would wrap this path into os.path.normpath().

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +                return_value=self.fake_audio_file_spec_set.audio_data).start()
Since you are only testing a single method a setUp and tearDown method are overkill and make the code a little bit harder to read. I would actually remove them and only write a single test class, that checks if the calculate_gain_difference_to_target and np.multiply methods are called correctly.

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +            )
I don't think it is necessary to create a full AudioFileSpecSet from scratch. 
Since in Python, everything can be mocked you can also simply create a `self.fake_audio_file_spec_set = mock.MagicMock()`.

In order to set a return value for a specific function or data entry from the fake_audio_file_spec_set, you can use:
`self.fake_audio_file_spec_set.audio_data = fake_audio_data`

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +        self.mock_np_multiply.stop()
I don't think the tear-down method is necessary. You are only testing a single method, not even parameterized.

According to the YAGNI principle:
> "You aren't gonna need it" is a principle which arose from extreme programming that states a programmer should not add functionality until deemed necessary.

2023-04-16 13:51 UTC, y-brehm commented on tests/unit/loudness_processing/test_align_waveform_to_target.py
> +
If I would write this class, I would set it up a lot more simple:
```python
import unittest
import mock

from wavealign.loudness_processing.align_waveform_to_target import align_waveform_to_target


class TestAlignWaveformToTarget(unittest.TestCase):
    @mock.patch('wavealign.loudness_processing.align_waveform_to_target.calculate_gain_difference_to_target')
    @mock.patch('wavealign.loudness_processing.align_waveform_to_target.np.multiply')
    def test_align_waveform_to_target(self, mock_np_multiply, mock_calculate_gain_difference_to_target):
        fake_audio_data = mock.MagicMock()
        mock_audio_file_spec_set = mock.MagicMock()

        mock_audio_file_spec_set.original_lufs = -10
        mock_audio_file_spec_set.audio_data = fake_audio_data
        mock_calculate_gain_difference_to_target.return_value = 0.63

        align_waveform_to_target(mock_audio_file_spec_set, -14)

        mock_calculate_gain_difference_to_target.assert_called_once_with(-10, -14)
        mock_np_multiply.assert_called_once_with(fake_audio_data, 0.63)
```

2023-04-19 17:20 UTC, maosi100 commented
thanks for the feedback! i remodeled the file in accordance to it. Tried to minimalize the effort and came out with almost the same implementation as yours

2023-04-23 14:31 UTC, y-brehm approved these changes

2023-04-23 14:58 UTC, merged