Issue/7/add support for all audio formats supported by rekordbox
y-brehm/waveAlign pull request #14
Opened 2023-04-24 19:51 UTC by SimonZimmer

Adds support for all audio formats that are supported by rekordbox.
Also makes sure that the files are encoded using the same attributes for bit_rate, sample rate, codec and artwork found in the original file. Tested using two files from my rekordbox library that were dragged out of place, processed and put back manually in the library. Didn't encounter any issues 🙏  

Additionally:
* Fix imports to make executing tests possible without calling `setup install` first
* Fix a bunch of cosmetics

Note:
Although wave_alignment desperately needs a refactor, it wasn't done here to focus on the feature first.

2023-04-26 08:23 UTC, y-brehm commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
Hmm, I guess the only thing missing here is actually converting to int24 and int32. I asked GPT4 to provide some information on how to modify the class. This is what came out:

Here is the modified class:
```python
import numpy as np
from numpy import ndarray
from numpy.iinfo import iinfo
from src.wavealign.data_collection.array_type_info import ArrayTypeInfo

class PcmFloatConverter:
    def is_pcm_encoded(self, signal: ndarray) -> bool:
        return signal.dtype.kind == 'i'

    def pcm_to_float(self, pcm_signal: ndarray) -> ndarray:
        array_type_info = self.__get_array_type_info(pcm_signal.dtype)
        output_dtype = 'float32'

        return (pcm_signal.astype(output_dtype)
                - array_type_info.offset) / array_type_info.abs_max

    def float_to_pcm(self, float_array: ndarray, output_dtype: str = 'int16') -> ndarray:
        array_type_info = self.__get_array_type_info(output_dtype)

        int_array = float_array * array_type_info.abs_max \
            + array_type_info.offset
        normalized_array = int_array.clip(array_type_info.min,
                                          array_type_info.max)

        return self.__to_int_dtype(normalized_array, output_dtype)

    def __get_array_type_info(self, dtype: str) -> ArrayTypeInfo:
        if dtype == 'int24':
            array_type_abs_max = 2 ** 23
            offset = -2 ** 23
            array_type_min = -2 ** 23
            array_type_max = 2 ** 23 - 1
        else:
            array_info = iinfo(dtype)
            array_type_abs_max = 2 ** (array_info.bits - 1)
            offset = array_info.min + array_type_abs_max
            array_type_min = array_info.min
            array_type_max = array_info.max

        return ArrayTypeInfo(array_type_abs_max,
                             offset,
                             array_type_min,
                             array_type_max)

    def __to_int_dtype(self, array: ndarray, dtype: str) -> ndarray:
        if dtype == 'int24':
            int32_array = array.astype(np.int32)
            int24_array = (int32_array[..., None] >> np.array([0, 8, 16], dtype=np.uint8)) & 0xFF
            return int24_array.view(np.uint8).reshape(array.shape + (-1,))
        else:
            return array.astype(dtype)
```

2023-04-26 08:24 UTC, y-brehm commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
I think the main problem is that the numpy iinfo function f does not support int24 data type directly:

> 
> In this modified version of the __get_array_type_info method, we create a custom dtype for int24 using the numpy.dtype constructor. We then calculate the absolute maximum value that can be stored in the int24 data type, which is based on the number of bits used to represent the data type.
> 
> We also calculate an offset value based on the minimum representable value and the absolute maximum value. Since int24 is a signed data type, the offset value is negative, and we set it to be -(2 ** (int24_dtype.itemsize * 8 - 1)).
> 
> Finally, we set the minimum and maximum representable values of the int24 data type, and return an instance of the ArrayTypeInfo class with the calculated values.
> 
> With this modification, the PcmFloatConverter class can now use the __get_array_type_info method to handle int24 data type.

2023-04-26 08:28 UTC, y-brehm commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
Since you have already stored the original bit rate, it can be utilized to determine the appropriate bit rate to be saved in.

2023-04-26 08:30 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_reader.py
> +            codec_name='eva01',
nice!

2023-04-26 08:38 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_writer.py
> +            self.fail('ExpectedException not raised')
Again more of a suggestion, but this is a really weird test structure: Instead of mocking only the private methods of the AudioFileWriter you actually mock functions from within those private methods (e.g. load file). I think if your private methods have a complexity that calls for testing (as they have in this case I would say), this points in the direction of a design flaw. Breaking apart the AudioFileWriter class as proposed in my comment above would allow you to also create a cleaner test-structure.

2023-04-26 08:42 UTC, y-brehm commented on tests/unit/data_collection/test_metadata_extractor.py
> +        mock.patch.stopall()
I think it would be easier to read if we stay consistent with the way we are writing tests. If you want to stick with that way, maybe create an issue that we modify the other tests (testing +2 methods), where it makes sense to also mock within the setUp function.

2023-04-26 08:50 UTC, y-brehm commented on tests/unit/data_collection/test_metadata_extractor.py
> +            self.fail('ExpectedException not raised')
Why not use:
`self.assertRaises(ValueError,  MetaDataExtractor().extract, 'some_path')`

2023-04-28 15:23 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_file_writer.py
> +        metadata.save()
All logic paths of this function are actually unit-tested using test_audio_file_writer.

I don't think this class is too complex which is why it's in here, but if you like to further increase granularity, I can do that.

2023-04-28 16:04 UTC, SimonZimmer commented on tests/unit/data_collection/test_audio_file_writer.py
> +            self.fail('ExpectedException not raised')
I think this comes down to our diverging understanding of the complexity of this class, which I already conceded to in the previous comments on this class.

> Instead of mocking only the private methods of the AudioFileWriter you actually mock functions from within those private methods
I don't think this is weid at all. This is fine, as long as the complexity is not too high. We also have countless examples of mocking behaviour of private methods to be tested as part of the public method in dearSerial, that have been approved by Chikashi. I also don't see any reason for mocking private methods of a class during testing. If you need to do that, then **this** would be a reason you should pull stuff out of a class.
There needs to be a balance between only super-simplistic free functions without any private functions and super complex god classes.
Let's discuss in person some time.

2023-04-28 16:09 UTC, SimonZimmer commented on tests/unit/data_collection/test_metadata_extractor.py
> +        mock.patch.stopall()
This pattern only makes sense, when you need to define the behaviour of a mock return value for multiple testing methods. Which is not the case for all tests. The only other test where this would make sense is the `audio_file_finder`. I adapted that.

2023-04-28 16:16 UTC, SimonZimmer commented on tests/unit/data_collection/test_metadata_extractor.py
> +            self.fail('ExpectedException not raised')
Because it provides slightly better testing feedback:

`self.assertRaises` only checks for the `ValueError`. But consider a situation, where a faulty change causes the tested code to raise another exception like `TypeError` for example. What happens is that the test throws an assert causing the `ERROR` stdout return code.
The same situation with the try/except block would cause the test to fail instead of error, and tell the dev that there was indeed an exception thrown, but it was not the one that is expected.

2023-04-28 16:39 UTC, SimonZimmer commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
Oh yeah, I guess your right about higher bit-rates than 16bit. I guess it would truncate anything to 16bit internally.
However, the value I'm saving in `AudioFileSpecSet.Metadata` is not the bit depth of a sample but rather the bitrate / second (which would include the bit depth but also is influenced by sample-rate).
We would need to check where we can get the bit-depth from and then adjust according to the custom type.

I don't think I have time for this before we fly so will need to create another issue regarding this for now:
https://github.com/y-brehm/waveAlign/issues/15

2023-04-28 16:43 UTC, SimonZimmer commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
I'm wondering though what happens when you encode a 24bit audio stream in 16bit underneath and then tell ffmpeg to encode in a bit-rate per second that presupposes a bit depth of 24bit 🤔 
I hope this doesn't mess up the readability of the file

2023-04-28 17:30 UTC, SimonZimmer commented on src/wavealign/data_collection/pcm_float_converter.py
> +        output_dtype = 'int16'
yeah you're right, I answered in detail to the other comment 👍

2023-04-29 10:33 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_writer.py
> +        metadata.save()
You are right, we should probably discuss this in person and leave it as it is for now. Both approaches have valid points, and it is more of a style thing I guess. 

I like the approach of more granularity and less private methods in general. In case I have to add a private method it is then such an implementation detail that mocking it in a test is sufficient. While this might lead to a ton of files I find that creating rules for testing is easier and the tests themselves become more readable. Googling this also shows that there are a lot of discussions about such things and it is probably not very expedient to discuss this over such a simple method as we are doing here.

2023-04-29 11:10 UTC, y-brehm requested changes

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/data_collection/test_metadata_extractor.py
> +            self.fail('ExpectedException not raised')
Hmm, I don't know if you should write code that can throw exceptions you are not expecting. I get your point that this might make sense in a test in order to tell you more about what happened. But I would feel more secure with handling my exceptions in the class itself and then just test if the correct exception is thrown in case something goes wrong.

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/data_collection/test_write_metadata.py
> +from src.wavealign.data_collection.write_metadata import write_metadata
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/data_collection/test_write_metadata.py
> +@mock.patch('src.wavealign.data_collection.write_metadata.load_file')
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/loudness_processing/test_calculation.py
> +from src.wavealign.loudness_processing.calculation import \
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/loudness_processing/test_calculation.py
> +    @mock.patch('src.wavealign.loudness_processing.calculation.gain_to_db')
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +from src.wavealign.data_collection.audio_file_spec_set import AudioFileSpecSet
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +                'src.wavealign.wave_alignment.os.path.normpath',
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +                'src.wavealign.wave_alignment.AudioFileFinder.find',
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +                'src.wavealign.wave_alignment.AudioFileWriter.write').start()
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +                'src.wavealign.wave_alignment.AudioFileReader.read',
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/wavealign/test_wave_alignment.py
> +                'src.wavealign.wave_alignment.align_waveform_to_target').start()
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/data_collection/test_metadata_extractor.py
> +from src.wavealign.data_collection.audio_metadata import AudioMetadata
since in the __init__.py for the test module you added:
```python
import os
import sys

PROJECT_PATH = os.getcwd()
SOURCE_PATH = os.path.join(
    PROJECT_PATH, 'src'
)
sys.path.append(SOURCE_PATH)
```
you should not need `src.` here (obviously you have to remove it for all the mocks as well). I double-checked this on my machine with your branch and it works without src. Why have you added it again for all the tests?

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/loudness_processing/test_calculation.py
> +    @mock.patch('src.wavealign.loudness_processing.calculation.db_to_gain')
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/loudness_processing/test_calculation.py
> +    @mock.patch('src.wavealign.loudness_processing.calculation.Meter')
remove `src.`

2023-04-29 11:10 UTC, y-brehm commented on tests/unit/loudness_processing/test_calculation.py
> +    @mock.patch('src.wavealign.loudness_processing.calculation.np.log10')
remove `src.`

2023-04-29 11:22 UTC, SimonZimmer commented on tests/unit/data_collection/test_metadata_extractor.py
> +from src.wavealign.data_collection.audio_metadata import AudioMetadata
Because it didn't work on my machine.
But you're right we shouldn't need it

2023-04-29 11:25 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_file_reader.py
> +    def __read_audio_file(self, file_path: str) -> ndarray:
No it cannot, since this method needs access to `self.__pcm_float_converter`.

2023-04-29 11:28 UTC, SimonZimmer commented on tests/unit/data_collection/test_metadata_extractor.py
> +            self.fail('ExpectedException not raised')
I'm not writing code that throws exceptions that I'm not expecting.
I'm writing a test that gives accurate information in the event the code **changes** which is a major reason for writing tests in the first place. I don't think it makes sense to discuss this further. Let's talk in person if there's more need to discuss.

2023-04-29 11:30 UTC, SimonZimmer commented on src/wavealign/data_collection/pcm_float_converter.py
> +                             array_type_max)
I don't think this is truncated, when changed to `int32`. But yes, as we discussed the other day we do need an integration test for the whole project. But that's something for another PR I'd say.

2023-04-29 11:34 UTC, SimonZimmer commented on src/wavealign/data_collection/metadata_extractor.py
> +            raise ValueError(f"Failed to read metadata for {file_path}")
I honestly don't see the benefit here.
But I also don't want to argue further, so I'll just do it.

2023-04-29 11:36 UTC, SimonZimmer commented on src/wavealign/data_collection/write_metadata.py
> +    metadata.save()
same as above

2023-04-29 18:17 UTC, y-brehm commented on src/wavealign/data_collection/audio_file_reader.py
> +    def __read_audio_file(self, file_path: str) -> ndarray:
Yo, sorry. Somehow missed this.

2023-04-29 18:20 UTC, y-brehm commented on src/wavealign/data_collection/metadata_extractor.py
> +            raise ValueError(f"Failed to read metadata for {file_path}")
https://stackoverflow.com/questions/16138232/is-it-a-good-practice-to-use-try-except-else-in-python

I think the answer by Raymond Hettinger here has quite some points, as to why it is always a good idea to use try-except in Python.

2023-04-29 18:20 UTC, y-brehm commented on src/wavealign/data_collection/write_metadata.py
> +    metadata.save()
https://stackoverflow.com/questions/16138232/is-it-a-good-practice-to-use-try-except-else-in-python

I think the answer by Raymond Hettinger here has quite some points, as to why it is most of the times a good idea to use try-except in Python.

2023-04-29 18:28 UTC, y-brehm approved these changes

2023-04-29 21:06 UTC, y-brehm commented
@SimonZimmer I just realized that you need to have ffmpeg installed on your machine in order to run this. Could you please add this to the README?

2023-04-30 09:22 UTC, merged