Issue/4/improve loudness calculation for non sausage tracks
y-brehm/waveAlign pull request #16
Opened 2023-04-30 14:30 UTC by y-brehm

This adds support for windowed loudness calculation with truncated windowing. This becomes a problem in case of a very large window size compared to the input audio (which will usually not happen). The result of the truncation basically is, that a different window size is used for processing compared to the window size defined by the user, in case the window count does not perfectly fit the length of the audio data. In a real-world scenario this difference will probably only consist of a few hundred samples max and therefore can probably be neglected.

I compared this method to zero-padding the input audio data (for cases when the input length is not a multiple of the window size) and realized that the performance decreased dramatically. I did not use a lot of time for the comparison though, so I added a TODO to investigate this further.

Other than that I also added PEAK and RMS loudness calculation for making this tool also useful for other audio batch-processing tasks. RMS is also faster than LUFS calculation but gives less accurate results.

I also addressed some refactorings since I had to touch a lot of stuff.

2023-05-01 12:51 UTC, SimonZimmer requested changes
Great application of polymorphism! 😍 

A few suggestions for general readability / cleanliness.
I don't really see the need of using classes when there is no caching or encapsulation involved.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/level_difference_calculator.py
> +    def calculate_level_difference_to_target_in_db(self,
This is a very trivial calculation that is just as easily read as it's body than it's name.
Since you also don't cache any state, it would be much simpler to just inline the body of the function where it is being used.

Consider:
https://refactoring.guru/inline-method

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/peak_calculator.py
> +        self.__db_gain_converter = DbGainConverter()
No state is actually cached here.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/rms_calculator.py
> +        self.__db_gain_converter = DbGainConverter()
No state is actually cached here.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/waveform_aligner.py
> +        self.__gain_difference_calculator = LevelDifferenceCalculator()
Since neither `LevelDifferenceCalculator` nor `DbGainCalculator` use state caching, there is no benefit of caching this here. Because there is also no private methods being used here, I again don't see a concrete reason for this being a class at all.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/waveform_aligner.py
> +                )
This would be fine if it was C++ and you could see from the function signature that a reference is going into the function. But because this is python, this function has the side-effect of modifying `audio_file_spec_set` which is not visible to the outside.
More pythonic would be to return `audio_file_spec_set` instead.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/window_cutter.py
> +            return []
This would mean that you return an empty array only if the ValueError is thrown.
Did you mean this?

```python
        try:
            ...
        except ValueError:
            print("audio")
            
        return []
```
That way, we return an empty array in case we don't throw an Exception but also don't return something in the try block.

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/loudness_processing/window_cutter.py
> +            print("audio")
Pls change this to something that describes better what the problem is

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/wave_alignment_processor.py
> +                if read_only is False:
`if not read_only`

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/wave_alignment_processor.py
> +                    if output_path is None:
`if not output_path`

2023-05-01 12:51 UTC, SimonZimmer commented on src/wavealign/wave_alignment_processor.py
> +                if read_only is False:
if you invert this and introduce a method that wraps the prints from L52-56, you can improve readability a lot by removing the nesting of a large block of code, while also avoiding double negation:

```python
if read_only:
    self.__print_processing_information(audio_levels, gain_calculation_strategy.value)
    return

self.__waveform_aligner.align_waveform_to_target(audio_file_spec_set, target_level)
...
self.__print_processing_information(audio_levels, gain_calculation_strategy.value)
```

2023-05-01 12:51 UTC, SimonZimmer commented on tests/unit/data_collection/test_audio_file_reader.py
> +            bit_rate='int16',
My initial value here was also not very good, but realistically this would be something like `16k` or `14k` so lets go with `16k`

2023-05-01 12:51 UTC, SimonZimmer commented on tests/unit/loudness_processing/test_peak_calculator.py
> +        mock_gain_to_db.assert_called_once_with(5)
This is more like a philosophical discussion but it's probably interesting:

The below tests test what is expected of the function for different edge cases, while this function tests if the `way` the results are achieved is matches exactly what was implemented.
I think the tests below better test the actual logic and are more easily to maintain, since it doesn't matter what tools are being used. Instead, it only matters that the give the same result.

2023-05-01 12:51 UTC, SimonZimmer commented on tests/unit/loudness_processing/test_rms_calculator.py
> +    def test_calculate_rms(self, mock_gain_to_db, mock_np_sqrt, mock_np_mean):
same argument as the previous comment

2023-05-01 12:51 UTC, SimonZimmer commented on tests/unit/loudness_processing/test_windowed_level_calculator.py
> +    def setUp(self) -> None:
for consistency: pls remove type hints for the functions in this file

2023-05-01 12:51 UTC, SimonZimmer commented on tests/unit/loudness_processing/test_windowed_level_calculator.py
> +    def setUp(self) -> None:
We should remove the `setUp` method here and inline everything, since there is only a single test here anyways so there is no code-duplication to remove.

2023-05-01 12:56 UTC, SimonZimmer commented
Pls also update the README according to the new available options :)

2023-05-01 13:42 UTC, maosi100 commented
General question: why do both of you use double underscores for defining "private" attributes and methods? Apart from the general "everything is public" approach in Python, aren't double underscores reserved for mangling methods to classes and single underscores should be used to indicate "private"?

see: https://stackoverflow.com/questions/7456807/should-i-use-name-mangling-in-python

2023-05-01 15:11 UTC, y-brehm commented on src/wavealign/batch_process_files.py
> +        gain_calculation_strategy=args.gain_calculation_strategy,
I would actually propose to leave it as it was but pack the selection into a private function as you suggested above. To me it makes way more sense that this is happening inside the AudioLevelExtractor.

2023-05-01 17:29 UTC, SimonZimmer commented
This is a sort of style choice coming from the job. The goal of this style is to write Python in such a way that comes as close as possible to traditional OOP languages like C++ (which is a very special style as one can argue).
Because encapsulation is a main concept of trad OOP, access to private methods of a class should be ideally impossible. While that's not doable in Python, the next best thing is name mangling because it is maximally inconvenient and a violation would be spotted with most ease.

I'm aware of some discussions on this but I also don't see any fixed standard for this, so it's a  style choice IMO.

Reading through the SO thread, it shows some agreement and some disagreement with this style, so I'd say it illustrates the lack of standard.

2023-05-02 07:58 UTC, SimonZimmer commented on src/wavealign/batch_process_files.py
> +        gain_calculation_strategy=args.gain_calculation_strategy,
Hmm ok I see the problem with the sample-rate parameter.
Yeah I agree, everything that makes sample-rate available earlier is probably dirtier than leaving it in AudioLevelExtractor 👍

2023-05-02 08:02 UTC, SimonZimmer commented on src/wavealign/loudness_processing/db_gain_converter.py
> +class DbGainConverter:
Hmm yeah, I do agree with chikashi here, since my obsessive-compulsive neurosis is firing when a feature like a class is implemented but not used. I guess there are different neurosis conflicting here.

> I thought about a third reason which is to combine logically similar functionality to a class so that I don't have to create two files for those functions. We could of course also be not so nitpicking about this and simply leave both functions in one file.

Yeah, totally, if a class was used before to combine logically similar functionality, why not use a file to do the same thing

2023-05-02 19:23 UTC, SimonZimmer commented on tests/unit/loudness_processing/test_peak_calculator.py
> +        mock_gain_to_db.assert_called_once_with(5)
> For some abstract pass-through classes with nearly no implementation, the mock way however stays the only option, besides not testing those at all (correct?).

Yes that is exactly how I understand the extreme programming philosophy as well.
Mocks in general are just crutches for excluding external functionality from the thing we want to test. If we don't need them for that, we probably shouldn't use them.

2023-05-02 19:24 UTC, SimonZimmer approved these changes

2023-05-02 20:03 UTC, merged