Enhancement/25/switch to toml
y-brehm/waveAlign pull request #38
Opened 2024-05-28 22:07 UTC by y-brehm

This solves the following issues:
#25
#26 
#27

Actually the new pyproject.toml is pretty nice. 
Make sure to install and use poetry for creating a virtual environment from now on.

2024-05-28 22:19 UTC, sabjorn requested changes

2024-05-28 22:19 UTC, sabjorn commented on pyproject.toml
> +[tool.poetry.dev-dependencies]
```suggestion
[tool.poetry.group.dev.dependencies]
```

this will make it so the dev dependencies are only added when you run:

```
poetry install --with dev
```

2024-05-28 22:19 UTC, sabjorn commented on README.md
> +poetry install
```suggestion
poetry install --with dev
```

2024-05-28 22:19 UTC, sabjorn commented on .github/workflows/run_tests.yml
> +          poetry install
```suggestion
          poetry install --with dev
```

2024-05-28 22:19 UTC, sabjorn commented on .github/workflows/run_tests.yml
> +          poetry run python -m unittest discover
```suggestion
          poetry run pytest
```

2024-05-28 22:19 UTC, sabjorn commented on README.md
does 

```
pip3 install git+https://github.com/y-brehm/waveAlign
```

still work after this change?

2024-05-31 11:26 UTC, y-brehm commented on README.md
@sabjorn Yes, as long as you use a version of pip3 that supports PEP 517/518, it works without problems. Since we also switched to python3.11 this should not be a problem.

2024-05-31 15:20 UTC, sabjorn approved these changes
Nice work—so clean

2024-06-02 16:26 UTC, merged