Issue/#29/optimize console output
y-brehm/waveAlign pull request #39
Opened 2024-05-31 07:52 UTC by maosi100

Added more descriptive information to output while reading and processing files.

2024-06-03 08:15 UTC, y-brehm approved these changes
Nice.
Just one comment regarding the traceback print message.

2024-06-03 08:15 UTC, y-brehm commented on src/wavealign/data_collection/audio_property_sets_reader.py
>                  traceback.print_exc()
As a note: Before merging pls. double check in how far this print influences the console output. I could imagine that this becomes a big mess in combination with the progress bar. So consider to remove it here and add more detailed info to the log. While the traceback print is very nice for debugging, this could also mess up the log file. Maybe we have to add a new issue to add a deeper layer of logging or we simply remove it for now.

2024-06-03 08:33 UTC, maosi100 commented on src/wavealign/data_collection/audio_property_sets_reader.py
>                  traceback.print_exc()
I think there's an option to include stack tranceback into exception logging. I'll check that in the current loggin PR and add that if possible. I'll remove the traceback from this PR for now.

2024-06-03 21:08 UTC, y-brehm requested changes
Overall, I noticed that the `logging_configuration.py' file is not consistent with the rest of the codebase (usually we put different classes and functions in separate files). Consider moving logging to its own subdirectory and splitting it into different files.

2024-06-03 21:08 UTC, y-brehm commented on tests/unit/data_collection/test_logging_configuration.py
> +        create_logging_config(output_path, verbose)
You could add additional tests, that check if the verbose branching works.

2024-06-03 21:16 UTC, y-brehm commented
Also this seems to be a duplicate of https://github.com/y-brehm/waveAlign/pull/42. If this was a mistake you can simply revert your changes here and apply requested changes on the quickfix branch.

2024-06-10 19:01 UTC, maosi100 commented on src/wavealign/data_collection/audio_property_sets_reader.py
>                  traceback.print_exc()
The progress bar interferes indeed with any write to stdout. There's a workaround by re-routing the logging output from stdout to tdqm.write() that I just implemented. Any messages to stdout will then be displayed above the progress bar like so and the progress bar still works:

<img width="1679" alt="Bildschirm­foto 2024-06-10 um 20 59 32" src="https://github.com/y-brehm/waveAlign/assets/111158251/f8fbe718-f98d-4ea9-b1e9-014f33d7dccf">

What do you think is this fine?

2024-06-10 19:12 UTC, y-brehm commented on src/wavealign/utility/logging/tqdm_console_handler.py
> +    def emit(self, record):
type hints missing.

2024-06-10 19:15 UTC, y-brehm approved these changes
YOLO

2024-06-10 19:25 UTC, maosi100 commented on src/wavealign/utility/logging/tqdm_console_handler.py
> +    def emit(self, record):
yes and the test is also missing, I wanted to make sure the output is alright before putting more work into it 🤠

2024-06-11 19:26 UTC, merged