Issue/30/optimize caching
y-brehm/waveAlign pull request #48
Opened 2024-06-21 16:43 UTC by y-brehm

2024-06-21 19:51 UTC, maosi100 commented on src/wavealign/caching/cache_manager.py
> +                    f"CacheManage has found {file_path} in cache. Skipping processing."
Typo: CacheManage

2024-06-21 19:51 UTC, maosi100 commented on src/wavealign/caching/cache_manager.py
> +        self.__logger.debug(f"CacheManage has not found {file_path} in cache. Processing.")
Typo: CacheManage

2024-06-21 20:10 UTC, maosi100 commented on src/wavealign/utility/convert_dict_to_dataclass.py
> +            raise ValueError(f"Additional field '{key}' found in the data dictionary.")
So this is more of a general topic regarding the control flow: I tried using this branch and this error was raised because I still had an old cache file in my test folder. I realized that the cache file is hidden and deleted it immediately. Next run worked smoothly. However I imagine a less experienced user having to "debug" this. Or we change something in future versions and people get errors due to old cache files.

Therefore: wouldn't it make sense for this function to return DataClassT | None and in case we encounter an error just output a message into the console?

2024-06-21 20:16 UTC, maosi100 commented on src/wavealign/caching/cache_manager.py
> +        self.__logger = logging.getLogger("CACHE MANAGER")
A comment on logger naming: best practice for naming loggers is to use logging.getLogger(__name__). This automatically names the logger in accordance to the package/module hierarchy (-> "wavealign.caching.cache_manager").

Since some logging messages are output directly to the user I find that using __name__ reduces read- and thus usability. Since we have a few different loggers now I wanted to mention that, since this is a deviation from best practices.

2024-06-21 20:37 UTC, maosi100 commented on src/wavealign/loudness_processing/audio_property_sets_processor.py
>              output = self.__generate_output_path(
wasn't changed, but wouldn't the variable be better called "output_path"?

2024-06-21 20:53 UTC, maosi100 commented on src/wavealign/caching/yaml_cache_processor.py
> +            raise ValueError("Cache path must be provided")
same comment as in convert_dict_to_dataclass.py. The application terminates if an error occurs within caching.

2024-06-29 19:56 UTC, y-brehm commented on src/wavealign/caching/cache_manager.py
> +        self.__logger = logging.getLogger("CACHE MANAGER")
I added the `__name__` to both new caching classes, since those only output on a debug level. Therefore the user won't see any cryptic class names (of course our class names are not cryptic by any means 😬).

2024-06-29 20:02 UTC, y-brehm commented on src/wavealign/utility/convert_dict_to_dataclass.py
> +            raise ValueError(f"Additional field '{key}' found in the data dictionary.")
Good point, since this can easily happen, I will just let the logger print something.

2024-06-29 21:14 UTC, y-brehm commented on src/wavealign/caching/yaml_cache_processor.py
> +            raise ValueError("Cache path must be provided")
TBH to me the ValueErrors in this class seem more like debug messages. I would suggest deleting them completely. I don't think it's possible for this class to get no `cache_path' and also a wrong input argument that is not of type `YamlCache'. If we were to use this pattern consistently, we would have to add these value errors or logging messages in every single class and for every single method.

2024-06-30 14:03 UTC, SimonZimmer requested changes

2024-06-30 14:03 UTC, SimonZimmer commented on src/wavealign/data_collection/audio_property_set_generator.py
>          audio_data = self.__audio_file_reader.read(file_path)
How about this for simplicity?

```py
    def generate(self, file_path: str) -> AudioPropertySet:
        audio_data = self.__audio_file_reader.read(file_path)
        last_modified = os.path.getmtime(file_path)
        metadata = self.__metadata_extractor.extract(file_path)

        lufs_level, peak_level = self.__get_cached_or_calculated_levels(
            file_path, audio_data, metadata.sample_rate
        )

        return AudioPropertySet(
            file_path=file_path,
            last_modified=last_modified,
            original_lufs_level=lufs_level,
            original_peak_level=peak_level,
            metadata=metadata,
        )

    def __get_cached_or_calculated_levels(
        self, file_path: str, audio_data: np.ndarray, sample_rate: int
    ) -> tuple[float, float]:
        if self.__levels_cache_finder:
            cached_levels = self.__levels_cache_finder.get_levels(file_path)
            if cached_levels:
                return cached_levels.lufs, cached_levels.peak

        return self.__get_audio_levels(audio_data, sample_rate)
```

2024-06-30 15:31 UTC, SimonZimmer approved these changes

2024-06-30 15:41 UTC, merged