Bug/mp3 issues diy
y-brehm/waveAlign pull request #50
Opened 2024-06-27 19:07 UTC by SimonZimmer

Fix the mp3 synchronisation issue by delegating mp3 processing to the new `mp3processor` C executable.
While I took care to reduce the original code to its absolute essentials, it's still too much refactoring work to get it done in time. (It's probably also better if we share some work so we'll be sharing the knowledge in the future)

So I made a new issue for the refactoring work: https://github.com/y-brehm/waveAlign/issues/49

Additionally:
* add CmakeLists.txt for cross-platform compilation
* add C executable compilation to gh-workflow
* add windows steps to gh-workflow
* refactor python tests for cross-platform compatibility
* remove m4a support
* add mac/windows command line argument parser for mp3processor

2024-06-28 12:38 UTC, maosi100 commented on src/wavealign/mp3processor/source/main.c
> +  fprintf(stderr, "Changing gain of %s by %f dB\n", filename, rightgainchange);
I suggest removing both prints or at least moving them into the python (un)compressed_file_processor(s) where they can be rerouted to tqdm.write()

2024-06-28 12:39 UTC, maosi100 commented on src/wavealign/mp3processor/source/main.c
> +    printf("Successfully changed gain of file %s\n", filename);
I suggest removing the print or at least moving it into the python (un)compressed_file_processor(s) where it can be rerouted to tqdm.write()

2024-06-28 12:39 UTC, maosi100 commented on src/wavealign/mp3processor/source/main.c
> +        fprintf(stderr, "Error: Could not change gain of file %s\n", filename);
I suggest removing the print or at least moving it into the python (un)compressed_file_processor(s) where it can be rerouted to tqdm.write()

2024-06-28 13:55 UTC, SimonZimmer commented on src/wavealign/mp3processor/source/main.c
> +		while (fillBuffer(0));
Yes, this is expected and to be solved with the tech-debt

2024-06-28 13:56 UTC, SimonZimmer commented on src/wavealign/mp3processor/source/main.c
> +    printf("Successfully changed gain of file %s\n", filename);
yes, this is something to be solved in the refactoring:
https://github.com/y-brehm/waveAlign/issues/49

2024-06-28 13:56 UTC, SimonZimmer commented on src/wavealign/mp3processor/source/main.c
> +        fprintf(stderr, "Error: Could not change gain of file %s\n", filename);
Yes, this is something to be solved in:
https://github.com/y-brehm/waveAlign/issues/49

2024-06-28 13:58 UTC, SimonZimmer commented
Everything in main.c is subject to the refactoring, so if you have any comments for this specific file, pls add them as a comment to https://github.com/y-brehm/waveAlign/issues/49

2024-06-28 15:14 UTC, maosi100 commented on src/wavealign/mp3processor/source/main.c
> +  fprintf(stderr, "Changing gain of %s by %f dB\n", filename, rightgainchange);
Yes that'd be great, thanks!

2024-06-30 09:23 UTC, maosi100 commented on tests/unit/data_collection/test_audio_file_finder.py
> +        self.finder = AudioFileFinder()
I think we're more verbose with variable names in this library

2024-06-30 09:31 UTC, maosi100 approved these changes
Sick work 🥵 Only one minor comment regarding variable name verboseness.

2024-06-30 13:56 UTC, y-brehm requested changes
One structural optimisation for more consistency. I have not looked at the C-code, since it needs refactoring anyways.

2024-06-30 13:56 UTC, y-brehm commented on .github/workflows/run_tests.yml
> +          cmake --build . --config Release
So there is no setup necessary for cmake? Can this become a problem in the future? Probably not, right?

2024-06-30 13:56 UTC, y-brehm commented on src/wavealign/loudness_processing/audio_file_processor.py
> +            )
Hmm, I think a more consistent way of implementing this would be to use the strategy pattern with the use of an additional interface. (see `AudioLevelExtractor`, `WindowedLevelCalculator`, `IAudioLevelCalculator` and both actual level calculators (peak, lufs) for reference).
The interface could be called `IAudioFileProcessor`, and both the `UncompressedFileProcessor` and the `CompressedFileProcessor` could inherit from it. Depending on the file type, the appropriate class would be created and used for further processing. You could rename this class to `AudioFileProcessorManager` and let it handle the instantiation of the correct `AudioFileProcessor`.

2024-06-30 14:04 UTC, SimonZimmer commented on .github/workflows/run_tests.yml
> +          cmake --build . --config Release
Fortunately, the github workflow agents have it pre-installed 😎

2024-06-30 14:08 UTC, SimonZimmer commented on src/wavealign/loudness_processing/audio_file_processor.py
> +            )
Yeah, I also thought of that and would love to.
However, the issue is that the signature of `compressed_file_processor` and `uncompressed_file_processor` is not the same.

The latter requires `audio_data` as an additional argument, while the former only requires 3 args.
So the interface would need to have 4 arguments for its `process` function and one of the two implementations would have an unused argument.

2024-06-30 14:44 UTC, SimonZimmer commented on tests/unit/data_collection/test_audio_file_finder.py
> +        self.finder = AudioFileFinder()
yes, fixed 👍

2024-06-30 15:04 UTC, y-brehm commented on src/wavealign/loudness_processing/audio_file_processor.py
> +            )
Hmm, a way around that would be to actually give `audio_data`  as an initialization argument to the object. This way the signature of the process function could stay the same. Of course this needs to be taken into account during the creation of the object and it has to be recreated or updated as soon as `audio_data` changes.

2024-06-30 15:30 UTC, SimonZimmer commented on src/wavealign/loudness_processing/audio_file_processor.py
> +            )
True, but the object would be reconstructed every single time here then.
At this point we're really forcing a design pattern in there at the cost of creating unnecessary state and an unnecessary number of constructions. I honestly think it's more elegant like this.

2024-06-30 15:45 UTC, y-brehm commented on src/wavealign/loudness_processing/audio_file_processor.py
> +            )
Hmm, yeah I agree. However, from a clean code perspective it seems complicated. Especially since the process method now also exceeds the magic max 3 arguments rule. But it is kind of ok readable right now, so I'll just approve. Maybe we can refactor this with a more elegant solution in the future.

2024-06-30 15:46 UTC, y-brehm approved these changes

2024-07-01 10:28 UTC, merged