Issue/#47/update readme
y-brehm/waveAlign pull request #52
Opened 2024-07-01 12:15 UTC by maosi100

* Adjustment of Readme Headings
* Inclusion of lossy file handling
* General readability improvements

2024-07-02 06:16 UTC, y-brehm requested changes

2024-07-02 06:16 UTC, y-brehm commented on README.md
>  * [python >= 3.11](https://www.python.org/)
Hmm, we should maybe make clear that those are the requirements for an installation via pip. If you install via GitHub repo you also need cmake and a c compiler.

2024-07-02 06:16 UTC, y-brehm commented on README.md
>  pip3 install git+https://github.com/y-brehm/waveAlign
This currently does not fully install the package since the compilation of the c code is still necessary. We should probably add this here, until we have the final PiPy package ready (at this point also the link will change).

2024-07-02 06:16 UTC, y-brehm commented on README.md
>  * [python >= 3.11](https://www.python.org/)
Currently you actually need cmake and a c compiler for both ways.

2024-07-02 06:16 UTC, y-brehm commented on README.md
> +
Something I forgot during my issue: Could you add, that caching is only active when input and output folders are the same (only an input folder is provided)?

2024-07-02 06:16 UTC, y-brehm commented on README.md
> +All Rekordbox(r) supported file types **except .m4a** are supported:
what about aac?

2024-07-12 12:58 UTC, maosi100 commented on README.md
>  pip3 install git+https://github.com/y-brehm/waveAlign
I removed the installation via package manager since we will not support it

2024-07-12 13:00 UTC, maosi100 commented on README.md
> +All Rekordbox(r) supported file types **except .m4a** are supported:
.aac is not supported as we would need to change the mp3gain library

2024-07-18 13:44 UTC, y-brehm approved these changes
Pls just add .aac to unsupported formats as mentioned in my comment before merging.

2024-07-18 13:44 UTC, y-brehm commented on README.md
> +All Rekordbox(r) supported file types **except .m4a** are supported:
Therefore pls add **except .m4a, .aac** above.

2024-07-21 13:55 UTC, merged