Issue/53/momentary lufs and padding
y-brehm/waveAlign pull request #55
Opened 2024-07-18 13:40 UTC by y-brehm

Our window-cutter implementation was really weird and most likely wrong. I exchanged it with a zero padding window cutter that pads the audio with zeros so that an exact amount of windows can be processed. Additionally I fixed the LFUS-M window size to 400ms and added two more integration tests.

2024-07-18 21:24 UTC, sabjorn commented on tests/integration/test_files/4432fp_honse_noise_-10LUFS-M_stereo.wav
the return of HONSE!

2024-07-18 22:47 UTC, sabjorn requested changes

2024-07-18 22:47 UTC, sabjorn commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +            ("1D pad two", np.array([1, 2, 3]), 4, np.array([1, 2, 3, 0])),
I don't understand what "pad one" and "pad two" mean in this context. In both cases the number of 0s that are padding the array is 1...

2024-07-18 22:47 UTC, sabjorn commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +            ),
what is the difference between "large padding" and "larger than array"? they both seem to be testing the same thing...

2024-07-18 22:47 UTC, sabjorn commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +        )
this could be in your parameterized tests above

2024-07-18 22:47 UTC, sabjorn commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +        np.testing.assert_array_equal(result, np.array([1, 2, 3, 0]))
you already tested this in your paramaterized tests above

2024-07-18 22:47 UTC, sabjorn commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +        np.testing.assert_array_equal(result, expected_output)
add to paramaterized tests

2024-07-19 13:51 UTC, y-brehm commented on src/wavealign/loudness_processing/windowed_level_calculator.py
> +        print(f"Window size in ms: {window_size_in_samples}")
This is actually a debug message and should be deleted.

2024-07-19 13:52 UTC, y-brehm commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +            ("1D pad two", np.array([1, 2, 3]), 4, np.array([1, 2, 3, 0])),
It is about the multiple that is given as an argument to the function. I renamed the tests for clarification.

2024-07-19 14:00 UTC, y-brehm commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +            ),
Yeah I agree, they are quite similar. Subtile differences is the single row input array [[1, 2]] and the two-row input array [[1, 2], [3, 4]]. The naming is off again. I renamed them to "2D padding single row to larger multiple", "2D padding multi-row to larger multiple". If you think it is redundant I can also delete the first one but I think it doesn't hurt and those numpy arrays can become quite confusing from time to time. So I rather have a test too much.

2024-07-19 14:03 UTC, y-brehm commented on tests/unit/loudness_processing/test_pad_to_multiple.py
> +        np.testing.assert_array_equal(result, np.array([1, 2, 3, 0]))
Damn, you are right, I think this is a leftover.

2024-07-19 14:07 UTC, y-brehm commented on tests/integration/test_files/4432fp_honse_noise_-10LUFS-M_stereo.wav
![image](https://github.com/user-attachments/assets/ad256ec2-57df-4046-860e-ecec13674dda)

2024-07-19 15:54 UTC, sabjorn approved these changes

2024-07-19 16:43 UTC, merged