Issue/#2/add unit tests data collection
y-brehm/waveAlign pull request #8
Opened 2023-03-17 09:11 UTC by maosi100

Added test for audio_file_finder and audio_file_handler

2023-03-18 10:40 UTC, y-brehm requested changes
Awesome, I'm actually quite impressed. Nothing big, just some informational comments and small cosmetics.

2023-03-18 10:40 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +        self.fake_start_dir = "/my/fake/dir"
We have not yet agreed on something in this regard, but I would suggest only using `""` in the case of real string representations. For paths, I would stick to ''.

2023-03-18 10:40 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +    @mock.patch('os.walk')
Since the complexity of the method you are testing is not that high, it is ok to not also mock `__is_suported_audio_file`. 
However, theoretically, you could divide this test into two:
1. First test mocks every used method and just checks that those are called in the correct order and with the expected arguments.
2. Second test does not mock anything and checks for expected functionality.

This test now is kind of a mixture of both, which as mentioned is okay given the complexity of the method under test.

If you want to mock the private method of the class `AudioFileFinder` you have to demangle it first:
`@mock.patch('wavealign.data_collection.audio_file_finder.AudioFileFinder._AudioFileFinder__is_supported_audio_file')`

Also, please mock os.path.abspath and os.walk in the following way:
```python
@mock.patch('wavealign.data_collection.audio_file_finder.AudioFileFinder.os.path.abspath')
@mock.patch('wavealign.data_collection.audio_file_finder.AudioFileFinder.os.path.walk')
```

I'm actually surprised your way of mocking those methods works.

2023-03-18 10:40 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +        self.assertFalse(self.audio_file_finder._AudioFileFinder__is_supported_audio_file("fake_file_4.txt"))
Theoretically, you don't have to test this, since it is a private method and should be indirectly tested through the public method `find`.
Consider this thread:
https://softwareengineering.stackexchange.com/questions/380287/why-is-unit-testing-private-methods-considered-as-bad-practice

2023-03-18 10:40 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_handler.py
> +        self.fake_file_path = "/my/fake/dir/fake_file_1.wav"
'' instead of "".

2023-03-18 10:40 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_handler.py
> +                "artwork": self.fake_artwork
same as above.

2023-03-18 16:01 UTC, maosi100 commented on tests/unit/data_collection/test_audio_file_finder.py
> +    @mock.patch('os.walk')
Thanks for this comprehensive feedback 💕 I've adjusted the test_find function to have every callable mocked as you described for 1., see below:
```
    @mock.patch('wavealign.data_collection.audio_file_finder.os.path.abspath')
    @mock.patch('wavealign.data_collection.audio_file_finder.os.walk')
    @mock.patch('wavealign.data_collection.audio_file_finder.AudioFileFinder._AudioFileFinder__is_supported_audio_file')
    def test_find(self, mock_AudioFileFinder__is_supported_audio_file, mock_walk, mock_abspath):
        mock_abspath.return_value = self.fake_start_dir
        mock_walk.return_value = [
                ('/my/fake/dir', ["subdir"], ["fake_file_1.wav", "fake_file_2.txt"]),
                ('/my/fake/dir/subdir', [], ["fake_file_3.aiff"])
                ]
        mock_AudioFileFinder__is_supported_audio_file.side_effect = [True, False, True]

        fake_output = self.audio_file_finder.find(self.fake_start_dir)

        expected_output = [
                '/my/fake/dir/fake_file_1.wav',
                '/my/fake/dir/subdir/fake_file_3.aiff'
                ]

        mock_abspath.assert_called_once_with(self.fake_start_dir)
        mock_walk.assert_called_once_with(self.fake_start_dir)
        mock_AudioFileFinder__is_supported_audio_file.assert_has_calls([
            mock.call("fake_file_1.wav"),
            mock.call("fake_file_2.txt"),
            mock.call("fake_file_3.aiff")
            ])

        self.assertEqual(fake_output, expected_output)
```

It was necessary patch the os methods with the path above, as your option raised the following Error `ModuleNotFoundError: No module named 'wavealign.data_collection.AudioFileFinder'`

However, how would you then set up the functionality tests for 2. (especially the private method) without mocking anything? Wouldn't you at least need to set up a temporary filesystem for the os methods to work?

2023-03-18 16:02 UTC, maosi100 commented on tests/unit/data_collection/test_audio_file_finder.py
> +        self.assertFalse(self.audio_file_finder._AudioFileFinder__is_supported_audio_file("fake_file_4.txt"))
see above

2023-03-19 15:15 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +    @mock.patch('os.walk')
@maosi100 Sorry. The os path I provided was simply wrong. You did it the correct way now. 

Regarding the setup for test 2:
This was more of a theoretical suggestion. Since the complexity of the whole AudioFileFinder class is really not that high, it might be overkill to apply it here. You are right, you would have to set up some dummy data structure in for example a new _tests/resources/audio_file_finder_ directory. Feel free to do that, but I would say it is definitely not a must. Actually, an additional mixed test that just mocks out `os.walk` would also be sufficient. In this case, you have to make sure that you define a realistic return value for `os.walk`.

2023-03-19 15:59 UTC, maosi100 commented on tests/unit/data_collection/test_audio_file_finder.py
> +    @mock.patch('os.walk')
perfect, I went with the latter of only mocking os.walk. Should be fine now, thanks!

2023-03-19 16:33 UTC, y-brehm approved these changes
Nice. Please have a look at my comments before merging.

2023-03-19 16:33 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +            ])
'' instead of "".

2023-03-19 16:33 UTC, y-brehm commented on tests/unit/data_collection/test_audio_file_finder.py
> +                ('/my/fake/dir/subdir', [], ["fake_file_3.aiff"])
same here.

2023-03-19 16:33 UTC, y-brehm commented on src/wavealign/loudness_processing/align_waveform_to_target.py
> +    audio_file_spec_set.audio_data = np.multiply(audio_file_spec_set.audio_data, gain_factor)
This looks like the changes from your other (already merged) PR. If you don't want them to show up here, you can always do an interactive rebase on main again. This also makes sure that there won't be any merge conflicts.  If you have never done this we can do it together at some point. It can feel a little sketchy since you have to force-push your changes in the end.

2023-03-19 17:02 UTC, maosi100 commented on src/wavealign/loudness_processing/align_waveform_to_target.py
> +    audio_file_spec_set.audio_data = np.multiply(audio_file_spec_set.audio_data, gain_factor)
yes I rebased from main after the hotfix and then popped my stashed changes on this branch. I feel this lead to this issue I couldn't resolve. Let's have a look together for interactive rebase before merging. 🤝

2023-03-19 17:27 UTC, merged